[font]
size = 12.0

[font.normal]
family = "Monaspace Neon NF"

[font.bold]
family = "Monaspace Neon NF"
style = "Bold"

[font.italic]
family = "Monaspace Neon NF"
style = "Italic"

[font.bold_italic]
family = "Monaspace Neon NF"
style = "Bold Italic"

