[font]
size = 15.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"


[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"
